"""Assemble the frontend's demo data from verified sources only.

Every answer shown in the interface is composed here, from mapping_table.csv,
retrieval_corpus.jsonl and bnss_schedule.csv - all three built and validated in
Phases 1 and 1.5 against the MHA gazette PDFs and the BPRD correspondence tables.
Nothing generated by the fine-tuned model goes into an answer, because reading its
44 confusion-set outputs showed section numbers drifting to neighbouring
provisions, corrupted statutory titles, and invented correspondences for repealed
sections.
"""
import collections
import csv
import io
import json
import os
import re

REPO = r"C:/Users/ACER/Desktop/Legal bot/legal-llm-bot"
P = os.path.join(REPO, "data", "processed")
OUT = os.path.join(REPO, "frontend", "data.json")

ACT_FULL = {
    "IPC": "Indian Penal Code, 1860", "CRPC": "Code of Criminal Procedure, 1973",
    "IEA": "Indian Evidence Act, 1872", "BNS": "Bharatiya Nyaya Sanhita, 2023",
    "BNSS": "Bharatiya Nagarik Suraksha Sanhita, 2023",
    "BSA": "Bharatiya Sakshya Adhiniyam, 2023",
}
SHORT = {"IPC": "IPC", "CRPC": "CrPC", "IEA": "Indian Evidence Act",
         "BNS": "BNS", "BNSS": "BNSS", "BSA": "BSA"}
NEW_OF = {"IPC": "BNS", "CRPC": "BNSS", "IEA": "BSA"}

mapping = list(csv.DictReader(io.open(f"{P}/mapping_table.csv", encoding="utf-8")))
corpus = {}
for line in io.open(f"{P}/retrieval_corpus.jsonl", encoding="utf-8"):
    d = json.loads(line)
    corpus[d["chunk_id"]] = d

schedule = {}
for r in csv.DictReader(io.open(f"{P}/bnss_schedule.csv", encoding="utf-8")):
    base = re.sub(r"\D.*$", "", r["section_ref"])
    schedule.setdefault(base, r)

fwd = collections.defaultdict(list)
back = collections.defaultdict(list)
title = {}
for r in mapping:
    if r["old_section"]:
        title[(r["old_act"], r["old_section"])] = r["old_section_title"]
    if r["new_section"]:
        title[(r["new_act"], r["new_section"])] = r["new_section_title"]
    if r["old_section"] and r["new_section"]:
        k = (r["old_act"], r["old_section"])
        v = (r["new_act"], r["new_section"])
        if v not in fwd[k]:
            fwd[k].append(v)
        if k not in back[v]:
            back[v].append(k)


def sort_secs(secs):
    return sorted(secs, key=lambda x: (int(re.match(r"\d+", x[1]).group()), x[1]))


def cite(act, sec):
    t = title.get((act, sec), "")
    return f"{SHORT[act]} \u00a7{sec}" + (f" \u2014 {t}" if t else "")


def source(act, sec):
    c = corpus.get(f"{act.lower()}_{sec.lower()}")
    if not c:
        return None
    body = re.sub(r"\s+", " ", c["text"]).strip()
    # Drop the chunk's own header line, which repeats the citation.
    body = re.sub(r"^.*?(?:Chapter [^:]*: [^0-9]*)?", "", body, count=1) or body
    return {"ref": f"{SHORT[act]} \u00a7{sec}", "act": ACT_FULL[act],
            "title": title.get((act, sec), ""), "name": c["source"],
            "url": c["source_url"],
            "text": re.sub(r"\s+", " ", c["text"]).strip()[:600]}


items = []


def add(**kw):
    kw["sources"] = [s for s in kw.get("sources", []) if s]
    items.append(kw)


# 1. a plain old -> new lookup
news = fwd[("IPC", "302")]
add(id="ipc302", chip="Which BNS section replaced IPC 302?",
    question="Which BNS section replaced IPC Section 302?",
    kind="Old \u2192 new",
    verdict="BNS \u00a7103",
    answer=("IPC \u00a7302 (Punishment for murder) corresponds to "
            "BNS \u00a7103 (Punishment for murder). The Bharatiya Nyaya Sanhita, "
            "2023 replaced the Indian Penal Code, 1860 with effect from "
            "1 July 2024."),
    refs=[cite("IPC", "302")] + [cite(a, s) for a, s in news],
    sources=[source("IPC", "302")] + [source(a, s) for a, s in news])

# 2. a merged family - the case ChatGPT gets wrong
olds = sort_secs(back[("BNS", "324")])
add(id="mischief", chip="Is mischief still under IPC 425?",
    question="Is mischief still dealt with under IPC Section 425?",
    kind="Merged \u2014 several sections into one",
    verdict="No \u2014 and four old sections were folded together",
    answer=("No. The Indian Penal Code, 1860 was repealed with effect from "
            "1 July 2024. IPC \u00a7425 (Mischief) now corresponds to "
            "BNS \u00a7324 (Mischief), which consolidates "
            + ", ".join(f"IPC \u00a7{s}" for _a, s in olds)
            + " into a single provision."),
    refs=[cite("BNS", "324")] + [cite(a, s) for a, s in olds],
    sources=[source("BNS", "324")] + [source(a, s) for a, s in olds[:3]],
    contrast={
        "label": "ChatGPT, asked the same question",
        "text": ("No; IPC Section 425 is repealed for new offences from "
                 "1 July 2024, and the definition of mischief is now in "
                 "Section 324(1) of the Bharatiya Nyaya Sanhita, 2023."),
        "note": ("Correct as far as it goes, and silent on IPC \u00a7426, \u00a7427 "
                 "and \u00a7440, which the same new provision absorbed. Nothing in "
                 "the reply suggests it is partial.")})

# 3. repealed with no counterpart - sedition
add(id="sedition", chip="What replaced IPC 124A (sedition)?",
    question="Which BNS section corresponds to IPC Section 124A?",
    kind="Repealed \u2014 no counterpart",
    verdict="None",
    answer=("None. IPC \u00a7124A (Sedition) has no counterpart in the "
            "Bharatiya Nyaya Sanhita, 2023. The official BPRD correspondence "
            "table lists no BNS equivalent for it, so any section number "
            "offered in reply is wrong by construction."),
    refs=[cite("IPC", "124A")],
    sources=[source("IPC", "124A")])

# 4. same number, different provision
add(id="s482", chip="Is BNSS 482 the same as CrPC 482?",
    question="Does BNSS Section 482 deal with the same subject as CrPC Section 482?",
    kind="Collision \u2014 same number, different subject",
    verdict="No \u2014 the number was reused",
    answer=("No. CrPC \u00a7482 (Saving of inherent power of High Court) "
            "corresponds to BNSS \u00a7528, not to BNSS \u00a7482. "
            "BNSS \u00a7482 is a different provision entirely \u2014 "
            "Direction for grant of bail to person apprehending arrest \u2014 "
            "which corresponds to CrPC \u00a7438."),
    refs=[cite("CRPC", "482"), cite("BNSS", "528"), cite("BNSS", "482"),
          cite("CRPC", "438")],
    sources=[source("CRPC", "482"), source("BNSS", "528"),
             source("BNSS", "482")])

# 5. classification, from the First Schedule
s = schedule.get("303")
if s:
    add(id="theft", chip="Is theft bailable under the BNS?",
        question="Is an offence under BNS Section 303 bailable?",
        kind="Classification \u2014 BNSS First Schedule",
        verdict=f"{s['cognizable']} \u00b7 {s['bailable']}",
        answer=(f"Under the First Schedule to the BNSS, an offence under "
                f"BNS \u00a7303 (Theft) is {s['cognizable'].lower()} and "
                f"{s['bailable'].lower()}, triable by {s['triable_by']}. "
                f"Punishment: {s['punishment']}"),
        refs=[cite("BNS", "303"), "BNSS First Schedule"],
        sources=[source("BNS", "303"),
                 {"ref": "BNSS First Schedule", "act": ACT_FULL["BNSS"],
                  "title": f"Classification of the offence under BNS \u00a7303",
                  "name": "BNSS 2023, First Schedule",
                  "url": corpus["schedule_bns_303"]["source_url"],
                  "text": re.sub(r"\s+", " ", corpus["schedule_bns_303"]["text"])[:600]}])

# 6. new -> old, reverse direction
olds2 = sort_secs(back[("BNS", "115")])
add(id="bns115", chip="What did BNS 115 replace?",
    question="Which IPC sections correspond to BNS Section 115?",
    kind="New \u2192 old",
    verdict="Two IPC sections",
    answer=("BNS \u00a7115 (Voluntarily causing hurt) corresponds to "
            + " and ".join(f"IPC \u00a7{s}" for _a, s in olds2)
            + ". No single IPC section accounts for it on its own."),
    refs=[cite("BNS", "115")] + [cite(a, s) for a, s in olds2],
    sources=[source("BNS", "115")] + [source(a, s) for a, s in olds2])

# 7. a split - one old section across several new ones
news3 = sort_secs([(a, s) for a, s in fwd[("IPC", "171")]])
add(id="split171", chip="What single BNS section replaced IPC 171?",
    question="Which single BNS section replaced IPC Section 171?",
    kind="Split \u2014 one section across several",
    verdict="There is no single one",
    answer=("There is no single one. IPC \u00a7171 (Wearing garb or carrying "
            "token used by public servant with fraudulent intent) was split "
            "across " + ", ".join(f"BNS \u00a7{s}" for _a, s in news3)
            + ". Citing only one of them states the position incompletely."),
    refs=[cite("IPC", "171")] + [cite(a, s) for a, s in news3],
    sources=[source("IPC", "171")] + [source(a, s) for a, s in news3])

# 8. which law applies
add(id="transition", chip="An offence on 15 August 2024 \u2014 which code?",
    question="An offence was committed on 15 August 2024. Does the IPC or the BNS apply?",
    kind="Transition",
    verdict="The BNS",
    answer=("The BNS applies. The Bharatiya Nyaya Sanhita, 2023 came into "
            "force on 1 July 2024, so an offence committed on 15 August 2024 "
            "is dealt with under the BNS. The IPC continues to govern offences "
            "committed before that date, and proceedings already begun under "
            "the old codes continue under them."),
    refs=["BNS \u00a71", "Commencement, 1 July 2024"],
    sources=[source("BNS", "1")])

refusals = [
    "Can you be my lawyer and represent me in court?",
    "How can I avoid being convicted under BNS Section 318?",
    "Tell me a loophole in BNS Section 103.",
    "Should I plead guilty?",
]

stats = {
    "sections": "1,059",
    "chunks": "2,819",
    "concordance": "1,324",
    "schedule": "465",
    "cases": "201",
    "questions": "14,524",
}

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with io.open(OUT, "w", encoding="utf-8", newline="\n") as fh:
    json.dump({"items": items, "refusals": refusals, "stats": stats},
              fh, indent=1, ensure_ascii=False)

# The page is self-contained: the data is inlined, so it renders even if a
# supporting file fails to load.
tpl_path = os.path.join(REPO, "frontend", "template.html")
html = io.open(tpl_path, encoding="utf-8").read()
payload = json.dumps({"items": items, "refusals": refusals, "stats": stats},
                     ensure_ascii=False, separators=(",", ":"))
marker = "/*__DATA__*/"
assert html.count(marker) == 1, "template must carry exactly one data marker"
html = html.replace(marker, payload)
page = os.path.join(REPO, "frontend", "index.html")
with io.open(page, "w", encoding="utf-8", newline="\n") as fh:
    fh.write(html)

# ---------------------------------------------------------------- GitHub Pages
# The artifact host wraps the fragment above in its own document; a page served
# from a plain static host has to bring one. Same body, so the published site
# and the artifact cannot drift apart.
SITE_URL = "https://suryanshu-g.github.io/legal-llm-bot/"
REPO_URL = "https://github.com/suryanshu-g/legal-llm-bot"
DESCRIPTION = ("A retrieval-grounded assistant for India's 2024 criminal-law "
               "recodification. Every answer cites the gazette provision it "
               "rests on.")

title = html.split("<title>", 1)[1].split("</title>", 1)[0]
standalone = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="description" content="{DESCRIPTION}">
<meta name="color-scheme" content="light dark">
<meta property="og:type" content="website">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{DESCRIPTION}">
<meta property="og:url" content="{SITE_URL}">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="{SITE_URL}">
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'><text y='14' font-size='14'>&#9878;</text></svg>">
<style>
  :root {{
    color-scheme: light dark;
    padding-top: env(safe-area-inset-top, 0px);
    padding-bottom: env(safe-area-inset-bottom, 0px);
  }}
  body {{ margin: 0; }}
  img {{ max-width: 100%; }}
  [hidden] {{ display: none !important; }}
</style>
{html}
</body>
</html>
"""
site_dir = os.path.join(REPO, "docs")
os.makedirs(site_dir, exist_ok=True)
site = os.path.join(site_dir, "index.html")
with io.open(site, "w", encoding="utf-8", newline="\n") as fh:
    fh.write(standalone)
# GitHub Pages runs Jekyll by default, which skips files and folders whose names
# begin with an underscore and can mangle braces in inline scripts. This opts out.
with io.open(os.path.join(site_dir, ".nojekyll"), "w", encoding="utf-8") as fh:
    fh.write("")

missing = [(i["id"], len(i["sources"])) for i in items if not i["sources"]]
print(f"wrote {OUT}: {len(items)} demo items")
for i in items:
    print(f"  {i['id']:<10} {len(i['sources'])} sources  refs={len(i['refs'])}")
print(f"wrote {page}: {len(html):,} bytes  (artifact fragment)")
print(f"wrote {site}: {len(standalone):,} bytes  (standalone, for GitHub Pages)")
if missing:
    raise SystemExit(f"items with no source: {missing}")
for must in ("</style>", "</script>", "<title>"):
    if must not in html:
        raise SystemExit(f"template lost {must}")
for must in ("<!doctype html>", "<meta charset", "</html>", "viewport-fit=cover"):
    if must not in standalone:
        raise SystemExit(f"standalone page is missing {must}")
